######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 28 22:53:10 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lclang

# Input
SOURCES += main.cpp
